### ISSUE TITLE
Exact_Pacthes

### ISSUE THREAD

**Issue by yunyundong** [ducha-aiki/affnet#16]
After detecting a feature point by using `Hessian` detector, then we get a initial `x0,y0 and sigma0`.  The  range of `x0` is [0, width-1], the range of `y0` is [0, height-1], `sigma0=power(2, i/L), i is the index of level, and L is the number of levels in a octave` . Then we further fintune the location of `x0` and `y0` and optimize the value of `sigma0`, and get the final `x1,y1 and sigma1`. 
Now, we assume the feature point located in the 0th octave and 2th level. According to the `x1, y1, and sigma1`, we crop a `64*64` patch from the `DoG` in the 0th octave and 2th level. Here,  a affine transform matrix is constructed as `LAF=[sigma1,0,x1;0,sigma1,y1]`  to crop the patch. Note, the range of sigma1 should be [1, 2].  
About the sigma1, can I understand it is a radius? namely, centered at point `(x1,y1)` in the DoG, then the area within the radius are croped and then resampled to 64*64 patch?

**Comment by ducha-aiki** [comment]
Yes, you are right. But.
1)  remember that sigma1 then is multiplied by coef. of the current octave. E.g. if octave is 2x downscaled. then coef is 2
2) Moreover, for description, there is "measurement region scale" mrScale, typically equal to 3sqrt(3)  or 5:

http://cmp.felk.cvut.cz/~chum/papers/perdoch-cvpr09.pdf

![image](https://user-images.githubusercontent.com/4803565/46602492-a8567400-caf0-11e8-93fa-b2d34a599133.png)

**Comment by yunyundong** [comment]
>remember that sigma1 then is multiplied by coef. of the current octave. E.g. if octave is 2x downscaled. then coef is 2

the coef is 1.0/2 or 2 ?    for example,  the content range  covered by a pixel in one image from octave 2 is equal to the content range covered by 2*2 pixels in octave 1. So, the coef is should be equal to 1/2?


>Moreover, for description, there is "measurement region scale" mrScale, typically equal to 3sqrt(3) or 5:

So, ( assume that 0 is the original image size, no downsampling),  the `measurement region scale` in the octave N is larger N times than the one of 0th octave image, in terms of image content?

**Comment by ducha-aiki** [comment]
@yunyundong  Lets do the example.

Say, on level 0 octave 0 we have feature location (x,y). Default init_sigma is 1.6, so is it our sigma.
Therefore ScaleSpaceAffinePatchExtractor, if no orientation/affine module is used, would output following LAF:

[mr_region_scale * sigma, 0, x;
 0, mr_region_scale * sigma,  y] =

[8.31, 0, x;
 0, 8.31, y]

So our patch in term of image content would correspond to circle with diameter 2 * 8.31 = 16.62 px. Which is then resized to PS, 32x32 by default.

If we have level 0, octave 1 at feature location (x,y), then LAF would be:

[2 * mr_region_scale * sigma, 0, x;
 0, 2 * mr_region_scale * sigma,  y]

If we have level 1 or level 2, then radius would be a bit larger according to 

https://github.com/ducha-aiki/affnet/blob/7b57978d9b96f8481b89c0739aa5283c5e2e7f52/HandCraftedModules.py#L39

**Comment by yunyundong** [comment]
I can get your example. What I want to say is as follows:
 for level 0 in octave 0, the diameter is 2* 8.31=16.62 px
 for level 0 in octave 1, the diameter is  2 * 3sqrt(3)*1.6 =16.62px  (assume mr_region_sacle=3sqrt(3);)
Now, the image content covered by the region with diameter 16.0 pixel from level 0 in octave 1 is two larger than the image content covered by the region with diameter 16.62 . Because the octave is downsampled from octave 0 .  
 the coef 2 should be 1/2 so that the region from different octaves represent the same image content.

another example: a original image with  size 64*64 px, after downsample operation, it wil becom 32*32 ->16*16-> 8*8-> 4*4. Now , can I say the 4*4 image represent the same content range as the original 64*64 original image?

**Comment by ducha-aiki** [comment]
@yunyundong Yes, you can say it.
Regarding coefficient, I think, you are wrong. Inside the octave, it is always one. Octave is downsampled, we don`t need to account for it. But coefficient is 2 if you want to have go from "radius in octave image" to "radius in original image".

And yes, if you go other way round - to calculate "radius in octave" from "radius in original", then it is 1/2

**Comment by yunyundong** [comment]
In fact, I also suspect I am wrong. So, I am only curious  that when the index of octave become larger, the region clipped to resample to ps*ps also becomes larger.

**Comment by ducha-aiki** [comment]
@yunyundong Yes, exactly.

**Comment by yunyundong** [comment]
I  got it, thank you very much for your patient explanation.
