### ISSUE TITLE
Comparison to vl_covdet()

### ISSUE THREAD

**Issue by yunyundong** [ducha-aiki/affnet#17]
In [vl_covdet](http://www.vlfeat.org/matlab/vl_covdet.html) function, there are some parameters,  is it similar the corresponding parameters in LAF?
>PatchResolution 15 (SIFT) or 20 (LIOP, Patch)
The size of the patch R in pixel. Specifically, the patch is a square image of side 2*R+1 pixels.

It is the patchsize (PS), right?

>PatchRelativeExtent 7.5 (SIFT), 10 (LIOP), or 6 (Patch)
The extent E of the patch in the normalized feature frame. The normalized feature frame is mapped to the feature frame F detected in the image by a certain affine transformation (A,T) (see VL_PLOTFRAME() for details). The patch is a square [-E, E]^2 in the normalize frame, and its shape in the original image is the (A,T) of it.

For the `PatchRelativeExtent` parameter, is it the `measurement region scale`, namely `mrScale`? 

Besides, I want to know what's the difference the normalized  feature frame in the vl_covdet and the normalized LAF ? 
Thank you in advance.

**Comment by ducha-aiki** [comment]
>PatchResolution is the patchsize (PS), right?

Right

>For the PatchRelativeExtent parameter, is it the measurement region scale, namely mrScale?

Yes

>Besides, I want to know what's the difference the normalized feature frame in the vl_covdet and the normalized LAF ?

Unfortunately, I am not that familiar with vlfeat library to give you full comparison. But these two seems very similar, especially given that they should do the same thing, as in my implementation of Hessian Affine

> VL_COVDET(..., 'EstimateAffineShape', true) switches on affine adaptation, an algorithm [2] that attempts to estimate the affine covariant shape of each feature.
