### ISSUE TITLE
AffNetFastFullAff architecture missing

### ISSUE THREAD

**Issue by mihaidusmanu** [ducha-aiki/affnet#18]
I am currently trying to use the script you provide for "Hessian detector + AffNet + HardNet++ descriptors" ([`extract_geom_and_desc_upisup.py`](https://github.com/ducha-aiki/affnet/blob/master/examples/hesaffnet/extract_geom_and_desc_upisup.py)) and it seems that the `AffNetFastFullAff` architecture is missing from [`architectures.py`](https://github.com/ducha-aiki/affnet/blob/master/architectures.py). The closest matching architecture name is `AffNetFastFullConv` - is this the one that should be used?

Thanks a lot for your work!

**Comment by ducha-aiki** [comment]
@mihaidusmanu Thanks for catch.
AffNetFast is should be there and https://github.com/ducha-aiki/affnet/blob/master/examples/hesaffnet/hesaffnet.py should be used. 
 AffNetFastFullAff and https://github.com/ducha-aiki/affnet/blob/master/examples/hesaffnet/extract_geom_and_desc_upisupTh.py are from one not quite successfull experiment and give inferior results.

**Comment by mihaidusmanu** [comment]
Thank you for your prompt response. Here is a script using HesAffNet + HardNet (it saves the output to a npz file): [hesaffnet_and_desc_image.py.tar.gz](https://github.com/ducha-aiki/affnet/files/2543352/hesaffnet_and_desc_image.py.tar.gz).
