### ISSUE TITLE
Is the experiments of Oxford Dataset retrieval task using BoW available?

### ISSUE THREAD

**Issue by appleleaves** [ducha-aiki/affnet#19]
I do not find any BoW codes in the repository, but you report the BoW performance.
I am very interested in this experiment and hope you can help me!

**Comment by ducha-aiki** [comment]
Hi,

Things regarding feature extraction are here:

https://github.com/ducha-aiki/mods-light-zmq#if-you-need-to-extract-and-save-features-from-directory-with-images

These gives you features and geometry. Regarding BoW itself, unfortunately, it is lab`s proprietary matlab code.

You could try this ASMK from here, but it is not the same

 http://cmp.felk.cvut.cz/~toliageo/soft.html

**Comment by appleleaves** [comment]
When clustering with kmneas methods into 1M vocabulary, it takes a really long time and I do not see the end.
Any advises?

**Comment by ducha-aiki** [comment]
1)Use faiss https://github.com/facebookresearch/faiss
or 2)use approximate KNN method like kd-tree for calculating nearest cluster center.
