### ISSUE TITLE
why the validation of handcrafted Baumberg Iteration runs without orientation

### ISSUE THREAD

**Issue by Childhoo** [ducha-aiki/affnet#24]
Hi,
in the "train_AffNet_test_on_graffity.py", the AffFastnet is trained and validated on the 1th-6th image of Oxford viewpoint dataset.
For a test image, the features/affshape/orientation/descriptor are extracted and computed by using the following function (line 254-259)
```
def get_geometry_and_descriptors(img, det, desc, do_ori = True):
    with torch.no_grad():
        LAFs, resp = det(img,do_ori = do_ori)
        patches = det.extract_patches_from_pyr(LAFs, PS = 32)
        descriptors = desc(patches)
    return LAFs, descriptors
```
Note here, the do_ori is set to be True as default. 

For learned part, the method first detect features and use learned aff module to do affine shape estimation. As shown In the test() function (validation after each epoch)
(Line 264-267)
```
    model.eval()
    detector = ScaleSpaceAffinePatchExtractor( mrSize = 5.192, num_features = 3000,
                                          border = 5, num_Baum_iters = 1, 
                                          AffNet = model)
```
and (Line 286-288)
```
LAFs1, descriptors1 = get_geometry_and_descriptors(img1, detector, descriptor)
torch.cuda.empty_cache()
LAFs2, descriptors2 = get_geometry_and_descriptors(img2, detector, descriptor)
```
The class ScaleSpaceAffinePatchExtractor handles learned or handcrafted way to do feature detection, affine shape estimation and orientation for an input image.

For the handcrafted way, the processing is this
(Line 316-317)
```
        LAFs1, descriptors1 = get_geometry_and_descriptors(img1, detector, descriptor, False)
        LAFs2, descriptors2 = get_geometry_and_descriptors(img2, detector, descriptor, False)
```
as the do_ori is switched off here, the whole process will skip the orientation step as shown in the forward() function of class ScaleSpaceAffinePatchExtractor (SparseImgRepresenter.py)
```
        if do_ori:
            LAFs = self.getOrientation(LAFs, final_pyr_idxs, final_level_idxs)
```
If I understand correctly, this means for validation of the hand-crafted way, no orientation module is used, but the aff module used here is learned affine net. [If I understand wrong, please tell me and ignore the following question]

Here is my question, why for the learned affine module, the orientation is assigned with handcrafted orientation method but for the hand-crafted way, the orientation step is skipped? I think a fairer comparison here will be comparing learned affnet with handcrafted aff estimation method.  Thank you very much for you attention.

**Comment by ducha-aiki** [comment]
That is by no mean comparison. It is a kind of validation and sanity check if training works properly. 

Why off? Because according to the experiments, it is beneficial to learn ori and aff separately.

**Comment by Childhoo** [comment]
Thank you for answering me! I will close it.
