### ISSUE TITLE
About AffNet training(Fig.5)

### ISSUE THREAD

**Issue by coper16** [ducha-aiki/affnet#26]
Hi.
I read "Repeatability is not Enough".
I was very interested in it.
Therefore, I want to try to use program of AffNet training(Fig.5 in that report).
*AffNet>ST>Desc>HardNegC Loss(using Phototour dataset)
Is there sample code of this?

**Comment by ducha-aiki** [comment]
https://github.com/ducha-aiki/affnet/blob/master/train_AffNet_test_on_graffity.py

**Comment by coper16** [comment]
Thank you very much!
