### ISSUE TITLE
About train_OriNet_test_on_graffity.py

### ISSUE THREAD

**Issue by coper16** [ducha-aiki/affnet#27]
I have a question about train_OriNet_test_on_graffity.py.
It's about the test function.
I think that for "input_img_fname1" and "input_img_fname2", the same 3d point part is extracted as a 32 * 32 image and assigned to the model (AffNet, OriNet).
However, I don’t know how to identify and extract the same 3D points.
Perhaps you are doing it in ine116, line118 of https://github.com/ducha-aiki/affnet/blob/master/SparseImgRepresenter.py, can you tell me the detailed mechanism?

**Comment by ducha-aiki** [comment]
For the graffity it is easy: you just reproject keypoint to another image using homography
