### ISSUE TITLE
About the version of the python and pytorch

### ISSUE THREAD

**Issue by yangwill81** [ducha-aiki/affnet#29]
Could u pls tell me the version of the python and pytorch?
I can't run it sucussfully with python 3.7. Thanks a lot.

**Comment by ducha-aiki** [comment]
Python is 2.7, not 3.7
pytorch 0.4.0

**Comment by ducha-aiki** [comment]
Here is version, which runs with python 3.7 and torch 1.4.0
https://github.com/ducha-aiki/affnet/tree/pytorch1-4_python3
