### ISSUE TITLE
Ｈｏｗ to get feature's scale and orientation

### ISSUE THREAD

**Issue by Jchtaylor** [ducha-aiki/affnet#30]
The output format is u v a b c
 How can I get scale and orientation for the feature point
Thanks

**Comment by ducha-aiki** [comment]
First, convert from ellipse format to LAF.
Ellipse is what you have, tensor of [x y a b c], shape (N, 5)
https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.ellipse_to_laf

Then you could you function to get scale
https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.get_laf_scale 


and kornia.feature.get_laf_orientation for orientation

**Comment by Jchtaylor** [comment]
Thanks, I can get scale from kornia.feature.get_laf_scale, but I can't get orientation from get_laf_orientation

module 'kornia.feature' has no attribute 'get_laf_orientation'

**Comment by ducha-aiki** [comment]
Install latest kornia from git, not from pipy:

pip install git+https://github.com/kornia/kornia.git

**Comment by Jchtaylor** [comment]
I tried it and it works well, but I found the second element of all the features' laf matrix are zero, which shows all the features' orientation are zero?  Does that make sense?

**Comment by ducha-aiki** [comment]
Sure, becuase x y a b c format does not contain orientation information, only feature affine shape and scale

**Comment by Jchtaylor** [comment]
Any other way to get orientation?

**Comment by ducha-aiki** [comment]
Run local feature orientation estimator for this. 
https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.PatchDominantGradientOrientation
Or OriNet
https://github.com/ducha-aiki/affnet/blob/master/pretrained/OriNet.pth
