### ISSUE TITLE
RuntimeError: [enforce fail at CPUAllocator.cpp:47] 

### ISSUE THREAD

**Issue by zhangch-ss** [ducha-aiki/affnet#32]
Hello, I tried to run affnet, there was an error.
RuntimeError: [enforce fail at CPUAllocator.cpp:47] ((ptrdiff_t)nbytes) >= 0. alloc_cpu() seems to have been called with negative number: 18446744072009756672
I started to think it was a memory problem, but my computer's memory is 64G.
I choose two data sets to run successfully, but more than three show this problem.
can you tell me the reason？thank you very much！

**Comment by ducha-aiki** [comment]
Hi,

What is the image size you are working on? Could you post the problematic image here?

**Comment by zhangch-ss** [comment]
thank you for your reply！
The dataset I used is 
![image](https://user-images.githubusercontent.com/57099533/82750208-12fd1600-9de1-11ea-8f51-d1f5814940e2.png) 6 dataset
(liberty.pt,liberty_harris.pt,notredame.pt,notredame_harris.pt,yosemite.pt,yosemite_harris.pt)
when  ./run_me.sh 
An error occurred   RuntimeError: [enforce fail at CPUAllocator.cpp:47] ((ptrdiff_t)nbytes) >= 0. alloc_cpu() seems to have been called with negative number: 18446744072009756672
when I use tow dataset
![image](https://user-images.githubusercontent.com/57099533/82750387-658b0200-9de2-11ea-9a02-08405363aa3c.png)
(liberty.pt,notredame.pt)
Run successfully
I want to know why this problem occurs and how to solve it，Can you give me some advice？Thank you very much！

**Comment by zhangch-ss** [comment]
Hi,

I think I found the problematic dataset, It is yosemite.pt.

when I use 5 dataset (liberty.pt,liberty_harris.pt,notredame.pt,notredame_harris.pt,yosemite_harris.pt)
Run successfully

But I did not find the cause of the problem.

**Comment by ducha-aiki** [comment]
Might be it has some problems during generation. Try to delete the file and generate it again.
