### ISSUE TITLE
Just a curiosity on the tech report...

### ISSUE THREAD

**Issue by fb82** [ducha-aiki/affnet#4]
Hi,
I found your work very interesting. Well done!

Just one question/curiosity about the results of Fig.6 in the tech report: could you also report what it would happen if the Hessian matrix of the keypoint is used "as it is" to define the elliptical shape (i.e. a sort of 0-th Baumberg iteration), maybe with only a threshold on the ratio between the ellipse axes to discard too elongated ellipses (0.75 or below maybe could be a good value) ?

Thanks in advance for your reply

**Comment by ducha-aiki** [comment]
Hi,

It is interesting idea, I will try this. It is not that general, although - Baumberg iterations can be used with any detector, but for Hessian it comes for free, you are right :)
About threshold: 1/6 is used for all methods, so it would be fair to use the same here as well.

**Comment by ducha-aiki** [comment]
@fb82 I have added Hessian matrix based shape to https://github.com/ducha-aiki/affnet/tree/hessian-matrix-affine branch. 
Here are test on 10 illumination and 10 viewpoint images from HPatches (not full). As you can see, performance is much worse, than for no affine shape at all. 

![image](https://user-images.githubusercontent.com/4803565/35042449-06c28e62-fb89-11e7-9662-0f736147c753.png)
![image](https://user-images.githubusercontent.com/4803565/35042463-1d2483e0-fb89-11e7-9bef-75e43b8c5fd8.png)

**Comment by fb82** [comment]
Fine, thanks!

**Comment by ducha-aiki** [comment]
@fb82 Sorry, it is actually not that bad. 

First variant was with treating Hessian matrix as A matrix, while this one treats gxx, gxy, gyy as a,b,c in ellipse representation (inverse square root of A). So, still worse, but not that bad :) 

![image](https://user-images.githubusercontent.com/4803565/35043832-5ce44768-fb8e-11e7-89cf-ac9081cd01f1.png)

![image](https://user-images.githubusercontent.com/4803565/35043896-962ed088-fb8e-11e7-8fb3-81ff1fdecd2e.png)

**Comment by fb82** [comment]
Now results are more consistent, I think :) Thanks again!
