### ISSUE TITLE
Dataset used for pre-training?

### ISSUE THREAD

**Issue by underfitting** [ducha-aiki/affnet#7]
Hi,
(Thank you for recommending me hardnet. Now I use hesaffnet+hardnet and this works much better!)

Can you tell me about dataset you used for pre-training?
What dataset did you use to train each model (HardNet++.pth and pretrained/AffNet.pth	)?

**Comment by ducha-aiki** [comment]
Hi,

You are welcome :)
It is all stated in corresponding papers. 
HardNet++ - Brown dataset (DoG patches) + HPatches dataset.
AffNet = Brown dataset (DoG and Harris patches).
