### ISSUE TITLE
role of orientation net

### ISSUE THREAD

**Issue by IQ17** [ducha-aiki/affnet#9]
Hi thanks for the repo!

I would like to ask is that specially use a OriNet to rotate the patch, and then extract descriptor from the rotated patch necessary? I think most of descriptors are, at least claimed to be, rotation invariant. 

descriptor(rotate(raw_patch)) and descriptor(raw_patch), are they really differ much?

**Comment by ducha-aiki** [comment]
So far, I am not aware of any practically good "rotationally invariant descriptors". What is true, that if you rotate patch to small angle, like 5..may be 10 degrees, you would be able to match them. If more - no way.

Yes, descriptor(rotate(raw_patch)) and descriptor(raw_patch) really differ A LOT. You can check yourself, e.g. on this image sequence: http://www.robots.ox.ac.uk/~vgg/research/affine/det_eval_files/boat.tar.gz

**Comment by IQ17** [comment]
Hi, I think your paper can be understood as a decoupled spatial transformer network (when STN uses affine matrix), but the way you do affine shape parametrization is much more precise and may lead to higher accuracy.
